repos:
  cheribuild:
    url: https://github.com/CTSRD-CHERI/cheribuild.git
    commit: "<pin_a_known_good_commit_here>"

  cheri-cva6:
    url: https://github.com/Capabilities-Limited/cheri-cva6.git
    branch: "zcheri"

  opensbi:
    url: https://github.com/riscv-software-src/opensbi.git
    branch: "master"

  uboot:
    url: https://github.com/u-boot/u-boot.git
    branch: "master"

  bao:
    url: https://github.com/bao-project/bao-hypervisor.git
    branch: "master"
  
  bao-baremetal-guest:
    url: https://github.com/ninolomata/bao-baremetal-guest.git
    branch: "cva6-cheri"

  baremetal-demo:
    url: "https://github.com/your-org/cva6-cheri-baremetal-demo.git"
    branch: "main"

